/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package church_education;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Ebrahim
 */
public class NewServantF extends javax.swing.JFrame {

    /**
     * Creates new form NewServantF
     */
    LogIn login = new LogIn();
    Connection con = login.con;
    Persons person = new Persons(con);
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs;
    
    private String check = "";
    private String frname = "";
    private String frnumber = "";
    private String frchurch = "";
    private String stname = "";
    private String stname2 = "";
    private String area = "";
    
    private String name1 = "";
    private String name2 = "";
    private String name3 = "";
    private String name4 = "";
    private java.sql.Date date = null;
    private int flat;
    private int floor;
    private int house;
    private String street1 = "";
    private String street2 = "";
    private String father = "";
    private String gender = "";
    private String phone = "";
    private String mobile = "";
    private String family = "";
    private String job = "";
    private String education = "";
    private String mnumber = "";
    private String mjob = "";
    private String fnumber = "";
    private String fjob = "";
    private String servant[];
    
    private String sname1 = "";
    private String sname2 = "";
    private String sname3 = "";
    private String sname4 = "";
    private java.sql.Date sdate = null;
    private int sflat;
    private int sfloor;
    private int shouse;
    private String sstreet1 = "";
    private String sstreet2 = "";
    private String sfather = "";
    private String sgender = "";
    private String sphone = "";
    private String smobile = "";
    private String sfamily1 = "";
    private String sfamily2 = "";
    private String sjob = "";
    private String cname = "";
    private String cfamily1 = "";
    private String cfamily2 = "";
    
//    private javafx.scene.control.TextField textField = new javafx.scene.control.TextField();
    private ArrayList<String> streetsnames = new ArrayList<>();
    private ArrayList<String> areasnames = new ArrayList<>();
    private ArrayList<String> servantsnames = new ArrayList<>();
    private ArrayList<String> fathers = new ArrayList<>();
    private ArrayList<String> families = new ArrayList<>();
    private ArrayList<String> assistance = new ArrayList<>();
    private ArrayList<String> educations = new ArrayList<>();
    private AutoComplete2 ac = new AutoComplete2();
    
    
    public NewServantF() {
        initComponents();
        buttonGroup2.add(Smale);
        buttonGroup2.add(Sfemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        Cname = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Sname1 = new javax.swing.JTextField();
        Sname2 = new javax.swing.JTextField();
        Sname3 = new javax.swing.JTextField();
        Sname4 = new javax.swing.JTextField();
        Sfloor = new javax.swing.JTextField();
        Sstreet1 = new javax.swing.JTextField();
        Sstreet2 = new javax.swing.JTextField();
        Sfather = new javax.swing.JTextField();
        Sphone = new javax.swing.JTextField();
        Smobile = new javax.swing.JTextField();
        Sfamily1 = new javax.swing.JComboBox<>();
        Sjob = new javax.swing.JTextField();
        Sflat = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Sfamily2 = new javax.swing.JComboBox<>();
        Sfemale = new javax.swing.JRadioButton();
        Smale = new javax.swing.JRadioButton();
        Jsdate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        Cfamily = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        Cfamily2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        Shouse = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        AssestantFamily = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabel23.setBackground(java.awt.Color.white);
        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getStyle() | java.awt.Font.BOLD, jLabel23.getFont().getSize()+4));
        jLabel23.setText("اختار من ");

        Cname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CnameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CnameMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(222, 221, 220));

        jLabel24.setBackground(java.awt.Color.white);
        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getStyle() | java.awt.Font.BOLD, jLabel24.getFont().getSize()+4));
        jLabel24.setText("الاسم الاول");

        jLabel25.setBackground(java.awt.Color.white);
        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getStyle() | java.awt.Font.BOLD, jLabel25.getFont().getSize()+4));
        jLabel25.setText("الاسم الثانى");

        jLabel26.setBackground(java.awt.Color.white);
        jLabel26.setFont(jLabel26.getFont().deriveFont(jLabel26.getFont().getStyle() | java.awt.Font.BOLD, jLabel26.getFont().getSize()+4));
        jLabel26.setText("الاسم الثالث");

        jLabel27.setBackground(java.awt.Color.white);
        jLabel27.setFont(jLabel27.getFont().deriveFont(jLabel27.getFont().getStyle() | java.awt.Font.BOLD, jLabel27.getFont().getSize()+4));
        jLabel27.setText("الاسم الرابع");

        jLabel28.setBackground(java.awt.Color.white);
        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getStyle() | java.awt.Font.BOLD, jLabel28.getFont().getSize()+4));
        jLabel28.setText("تاريخ الميلاد");

        jLabel29.setBackground(java.awt.Color.white);
        jLabel29.setFont(jLabel29.getFont().deriveFont(jLabel29.getFont().getStyle() | java.awt.Font.BOLD, jLabel29.getFont().getSize()+4));
        jLabel29.setText("العنوان");

        jLabel30.setBackground(java.awt.Color.white);
        jLabel30.setFont(jLabel30.getFont().deriveFont(jLabel30.getFont().getStyle() | java.awt.Font.BOLD, jLabel30.getFont().getSize()+4));
        jLabel30.setText("رقم الشقة");

        jLabel31.setBackground(java.awt.Color.white);
        jLabel31.setFont(jLabel31.getFont().deriveFont(jLabel31.getFont().getStyle() | java.awt.Font.BOLD, jLabel31.getFont().getSize()+4));
        jLabel31.setText("الدور");

        jLabel32.setBackground(java.awt.Color.white);
        jLabel32.setFont(jLabel32.getFont().deriveFont(jLabel32.getFont().getStyle() | java.awt.Font.BOLD, jLabel32.getFont().getSize()+4));
        jLabel32.setText("اسم الشارع");

        jLabel33.setBackground(java.awt.Color.white);
        jLabel33.setFont(jLabel33.getFont().deriveFont(jLabel33.getFont().getStyle() | java.awt.Font.BOLD, jLabel33.getFont().getSize()+4));
        jLabel33.setText("متفرع من");

        jLabel34.setBackground(java.awt.Color.white);
        jLabel34.setFont(jLabel34.getFont().deriveFont(jLabel34.getFont().getStyle() | java.awt.Font.BOLD, jLabel34.getFont().getSize()+4));
        jLabel34.setText("اب الاعتراف ابونا");

        jLabel35.setBackground(java.awt.Color.white);
        jLabel35.setFont(jLabel35.getFont().deriveFont(jLabel35.getFont().getStyle() | java.awt.Font.BOLD, jLabel35.getFont().getSize()+4));
        jLabel35.setText("النوع");

        jLabel36.setBackground(java.awt.Color.white);
        jLabel36.setFont(jLabel36.getFont().deriveFont(jLabel36.getFont().getStyle() | java.awt.Font.BOLD, jLabel36.getFont().getSize()+4));
        jLabel36.setText("التليفون");

        jLabel37.setBackground(java.awt.Color.white);
        jLabel37.setFont(jLabel37.getFont().deriveFont(jLabel37.getFont().getStyle() | java.awt.Font.BOLD, jLabel37.getFont().getSize()+4));
        jLabel37.setText("الموبايل");

        jLabel38.setBackground(java.awt.Color.white);
        jLabel38.setFont(jLabel38.getFont().deriveFont(jLabel38.getFont().getStyle() | java.awt.Font.BOLD, jLabel38.getFont().getSize()+4));
        jLabel38.setText("الاسرة ");

        jLabel39.setBackground(java.awt.Color.white);
        jLabel39.setFont(jLabel39.getFont().deriveFont(jLabel39.getFont().getStyle() | java.awt.Font.BOLD, jLabel39.getFont().getSize()+4));
        jLabel39.setText("العمل");

        Sname1.setFont(Sname1.getFont().deriveFont(Sname1.getFont().getSize()+4f));

        Sname2.setFont(Sname2.getFont().deriveFont(Sname2.getFont().getSize()+4f));

        Sname3.setFont(Sname3.getFont().deriveFont(Sname3.getFont().getSize()+4f));

        Sname4.setFont(Sname4.getFont().deriveFont(Sname4.getFont().getSize()+4f));

        Sfloor.setFont(Sfloor.getFont().deriveFont(Sfloor.getFont().getSize()+4f));
        Sfloor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SfloorKeyPressed(evt);
            }
        });

        Sstreet1.setFont(Sstreet1.getFont().deriveFont(Sstreet1.getFont().getSize()+4f));
        Sstreet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sstreet1MouseEntered(evt);
            }
        });

        Sstreet2.setFont(Sstreet2.getFont().deriveFont(Sstreet2.getFont().getSize()+4f));
        Sstreet2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sstreet2MouseEntered(evt);
            }
        });

        Sfather.setFont(Sfather.getFont().deriveFont(Sfather.getFont().getSize()+4f));
        Sfather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SfatherMouseEntered(evt);
            }
        });

        Sphone.setFont(Sphone.getFont().deriveFont(Sphone.getFont().getSize()+4f));
        Sphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SphoneKeyPressed(evt);
            }
        });

        Smobile.setFont(Smobile.getFont().deriveFont(Smobile.getFont().getSize()+4f));
        Smobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SmobileKeyPressed(evt);
            }
        });

        Sfamily1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sfamily1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Sfamily1MousePressed(evt);
            }
        });

        Sjob.setFont(Sjob.getFont().deriveFont(Sjob.getFont().getSize()+4f));

        Sflat.setFont(Sflat.getFont().deriveFont(Sflat.getFont().getSize()+4f));
        Sflat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SflatKeyPressed(evt);
            }
        });

        jLabel40.setBackground(java.awt.Color.white);
        jLabel40.setFont(jLabel40.getFont().deriveFont(jLabel40.getFont().getStyle() | java.awt.Font.BOLD, jLabel40.getFont().getSize()+4));
        jLabel40.setText("خدمة اخرى");

        Sfamily2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sfamily2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Sfamily2MousePressed(evt);
            }
        });

        Sfemale.setBackground(java.awt.Color.white);
        Sfemale.setFont(Sfemale.getFont().deriveFont(Sfemale.getFont().getStyle() | java.awt.Font.BOLD, Sfemale.getFont().getSize()+4));
        Sfemale.setText("انثى");
        Sfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SfemaleActionPerformed(evt);
            }
        });

        Smale.setBackground(java.awt.Color.white);
        Smale.setFont(Smale.getFont().deriveFont(Smale.getFont().getStyle() | java.awt.Font.BOLD, Smale.getFont().getSize()+4));
        Smale.setText("ذكر");

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getStyle() | java.awt.Font.BOLD, jButton2.getFont().getSize()+4));
        jButton2.setText("حفظ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel42.setBackground(java.awt.Color.white);
        jLabel42.setFont(jLabel42.getFont().deriveFont(jLabel42.getFont().getStyle() | java.awt.Font.BOLD, jLabel42.getFont().getSize()+4));
        jLabel42.setText("الاسرة");

        Cfamily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CfamilyMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CfamilyMousePressed(evt);
            }
        });

        jLabel43.setBackground(java.awt.Color.white);
        jLabel43.setFont(jLabel43.getFont().deriveFont(jLabel43.getFont().getStyle() | java.awt.Font.BOLD, jLabel43.getFont().getSize()+4));
        jLabel43.setText("خدمة اخرى");

        Cfamily2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cfamily2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Cfamily2MousePressed(evt);
            }
        });

        jButton3.setFont(jButton3.getFont().deriveFont(jButton3.getFont().getStyle() | java.awt.Font.BOLD, jButton3.getFont().getSize()+4));
        jButton3.setText("حفظ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Shouse.setFont(Shouse.getFont().deriveFont(Shouse.getFont().getSize()+4f));
        Shouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShouseKeyPressed(evt);
            }
        });

        jLabel54.setFont(jLabel54.getFont().deriveFont(jLabel54.getFont().getStyle() | java.awt.Font.BOLD, jLabel54.getFont().getSize()+4));
        jLabel54.setText("رقم المنزل");

        AssestantFamily.setFont(AssestantFamily.getFont().deriveFont(AssestantFamily.getFont().getSize()+4f));
        AssestantFamily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AssestantFamilyMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Sjob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sfamily2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Smobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sfamily1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(Jsdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Sname2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sname1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Sname3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sname4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(Sfemale)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Smale))
                                                .addComponent(Sstreet1)
                                                .addComponent(Sstreet2)
                                                .addComponent(Sfather))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Sflat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Sfloor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Shouse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(130, 130, 130))
                                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Cname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AssestantFamily, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cfamily, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cfamily2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(130, 130, 130))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 88, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AssestantFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Cfamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cfamily2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Sname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(Sphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Sname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Sname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(Smobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(Sname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(Sfamily1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(Sfamily2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(Sjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jsdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(60, 60, 60)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(Sflat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(Sfloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(Shouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(Sstreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(Sstreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(Sfather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sfemale)
                            .addComponent(Smale)
                            .addComponent(jLabel35))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CnameMouseEntered

    }//GEN-LAST:event_CnameMouseEntered

    private void CnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CnameMousePressed
        try {
            // TODO add your handling code here:
            assistance = person.getAssistance(AssestantFamily.getSelectedItem().toString());
            person.fillComboBox(Cname, assistance);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CnameMousePressed

    private void SfloorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SfloorKeyPressed
        String value = Sfloor.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Sfloor.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Sfloor.setEditable(false);
        }
    }//GEN-LAST:event_SfloorKeyPressed

    private void Sstreet1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sstreet1MouseEntered
        try {
            streetsnames = person.getStreetsNames();
            ac.autoComplete(Sstreet1, streetsnames);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Sstreet1MouseEntered

    private void Sstreet2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sstreet2MouseEntered
        try {
            streetsnames = person.getStreetsNames();
            ac.autoComplete(Sstreet2, streetsnames);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Sstreet2MouseEntered

    private void SfatherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SfatherMouseEntered
        try {
            fathers = person.getFathers();
            ac.autoComplete(Sfather, fathers);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SfatherMouseEntered

    private void SphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SphoneKeyPressed
        String value = Sphone.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Sphone.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Sphone.setEditable(false);
        }
    }//GEN-LAST:event_SphoneKeyPressed

    private void SmobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SmobileKeyPressed
        String value = Smobile.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Smobile.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Smobile.setEditable(false);
        }
    }//GEN-LAST:event_SmobileKeyPressed

    private void Sfamily1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sfamily1MouseEntered

    }//GEN-LAST:event_Sfamily1MouseEntered

    private void Sfamily1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sfamily1MousePressed
        try {
            // TODO add your handling code here:
            families = person.getFamilies();
            person.fillComboBox(Sfamily1, families);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Sfamily1MousePressed

    private void SflatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SflatKeyPressed
        String value = Sflat.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Sflat.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Sflat.setEditable(false);
        }
    }//GEN-LAST:event_SflatKeyPressed

    private void Sfamily2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sfamily2MouseEntered

    }//GEN-LAST:event_Sfamily2MouseEntered

    private void Sfamily2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sfamily2MousePressed
        try {
            // TODO add your handling code here:
            families = person.getFamilies();
            person.fillComboBox(Sfamily2, families);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Sfamily2MousePressed

    private void SfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SfemaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            sname1 = person.FixString(Sname1.getText());
            sname2 = person.FixString(Sname2.getText());
            if(sname1.isEmpty()){
                JOptionPane.showMessageDialog(null,  "رجاء ادخل اسم الخادم", "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(sname2.isEmpty()){
                JOptionPane.showMessageDialog(null, "رجاء ادخل الاسم الثانى ", "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sname3 = person.FixString(Sname3.getText());
            sname4 = person.FixString(Sname4.getText());
            if(Jsdate.getDate() != null)
            sdate = new java.sql.Date(Jsdate.getDate().getTime());
            if(!Sflat.getText().isEmpty())
            sflat = Integer.parseInt(Sflat.getText());
            if(!Sfloor.getText().isEmpty())
            sfloor = Integer.parseInt(Sfloor.getText());
            if(!Shouse.getText().isEmpty())
            shouse = Integer.parseInt(Shouse.getText());
            sstreet1 = Sstreet1.getText();
            sstreet2 = Sstreet2.getText();
            sfather = Sfather.getText();
            if(Sfemale.isSelected()){
                sgender = "Female";
            }else{
                sgender = "Male";
            }
            if(!Sphone.getText().isEmpty())
            sphone = Sphone.getText();
            if(!Smobile.getText().isEmpty())
            smobile = Smobile.getText();
            sfamily1 = (String)Sfamily1.getSelectedItem();
            sfamily2 = (String)Sfamily2.getSelectedItem();
            sjob = Sjob.getText();
            //            education = (String)Education.getSelectedItem();
            //            if(!Mnumber.getText().isEmpty())
            //                mnumber = Mnumber.getText();
            //            mjob = FixString(Mjob.getText());
            //            if(!Fnumber.getText().isEmpty())
            //                fnumber = Fnumber.getText();
            //            fjob = FixString(Fjob.getText());
            //            servant = Servant.getText().split("\\s+");
            int stID1 = -1;
            if(!sstreet1.isEmpty()){
                pst = (PreparedStatement) con.prepareStatement("SELECT StreetID FROM Streets WHERE StreetName = ? LIMIT 1");
                pst.setString(1, sstreet1);
                rs = pst.executeQuery();
                if(rs.next())
                stID1 = rs.getInt(1);
            }
            int stID2 = -1;
            if(!sstreet2.isEmpty()){
                pst = (PreparedStatement) con.prepareStatement("SELECT StreetID FROM Streets WHERE StreetName = ? LIMIT 1");
                pst.setString(1, sstreet2);
                rs = pst.executeQuery();
                if(rs.next())
                stID2 = rs.getInt(1);
            }
            int fatherID = -1;
            if(!sfather.isEmpty()){
                pst = (PreparedStatement) con.prepareStatement("SELECT FatherID FROM Fathers WHERE Name = ? LIMIT 1");
                pst.setString(1,sfather);
                rs = pst.executeQuery();
                if(rs.next())
                fatherID = rs.getInt(1);
            }

            //            int servantID = 0;
            //            if(servant.length == 4){
                //                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? AND ThirdName = ? AND FourthName = ? LIMIT 1");
                //                pst.setString(1, servant[0]);
                //                pst.setString(2, servant[1]);
                //                pst.setString(3, servant[2]);
                //                pst.setString(4, servant[3]);
                //                rs = pst.executeQuery();
                //                if(rs.next())
                //                    servantID = rs.getInt(1);
                //            }else if(servant.length == 3){
                //                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? AND ThirdName = ? LIMIT 1");
                //                pst.setString(1, servant[0]);
                //                pst.setString(2, servant[1]);
                //                pst.setString(3, servant[2]);
                //                rs = pst.executeQuery();
                //                if(rs.next())
                //                    servantID = rs.getInt(1);
                //            }else if(servant.length == 2){
                //                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? LIMIT 1");
                //                pst.setString(1, servant[0]);
                //                pst.setString(2, servant[1]);
                //                rs = pst.executeQuery();
                //                if(rs.next())
                //                    servantID = rs.getInt(1);
                //            }else{
                //                servantID = -1;
                //            }

            pst = (PreparedStatement) con.prepareStatement("select * from Persons where " +
                "FirstName = ? and (Mobile = ? or Telephon = ?)");
            pst.setString(1, sname1);
            pst.setString(2, smobile);
            pst.setString(3, sphone);
            rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "هذاالخادم  موجود بالفعل يمكنك البحث عنه عن طريق  ID : " + rs.getInt("PersonID"), "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }

            pst = (PreparedStatement) con.prepareStatement("INSERT INTO Persons(FirstName, SecondName, ThirdName, " +
                "FourthName, DOB, ApartmentNumber, FloorNumber, Job, Telephon, Mobile, Gender, FatherID, StreetID, " +
                "StreetID2, House)" +
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setString(1, sname1);
            pst.setString(2, sname2);
            pst.setString(3, sname3);
            pst.setString(4, sname4);
            pst.setDate(5, (java.sql.Date) sdate);
            pst.setInt(6, sflat);
            pst.setInt(7, sfloor);
            pst.setString(8, sjob);
            pst.setString(9, sphone);
            pst.setString(10, smobile);
            pst.setString(11, sgender);
            if(sfather.isEmpty())
                pst.setString(12, null);
            else
                pst.setInt(12, fatherID);
            if(sstreet1.isEmpty())
                pst.setString(13, null);
            else
                pst.setInt(13, stID1);
            if(sstreet2.isEmpty())
                pst.setString(14, null);
            else
                pst.setInt(14, stID2);
            pst.setInt(15, shouse);
            pst.executeUpdate();

            Sname1.setText("");
            Sname2.setText("");
            Sname3.setText("");
            Sname4.setText("");
            //            date.setDate(2020);
            Sflat.setText("");
            Sfloor.setText("");
            Sstreet1.setText("");
            Sstreet2.setText("");
            Sfather.setText("");
            buttonGroup2.clearSelection();
            Sphone.setText("");
            Smobile.setText("");
            Sjob.setText("");
            Shouse.setText("");

            int servantID = -1;
            rs = pst.executeQuery("Select LAST_INSERT_ID()");
            if(rs.next())
            servantID = rs.getInt(1);
            if(servantID != -1){
                pst = (PreparedStatement) con.prepareStatement("INSERT INTO Servants(ServantID) VALUES (?)");
                pst.setInt(1, servantID);
                pst.executeUpdate();
            }

            if(sfamily1 != null)
                person.addDistribution(sfamily1, servantID, 0);
            if(sfamily2 != null)
                person.addDistribution(sfamily2, servantID, 0);

            JOptionPane.showMessageDialog(null, "Done!", "Alert", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some thing wronge hapen!", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CfamilyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CfamilyMouseEntered

    }//GEN-LAST:event_CfamilyMouseEntered

    private void CfamilyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CfamilyMousePressed
        try {
            // TODO add your handling code here:
            families = person.getFamilies();
            person.fillComboBox(Cfamily, families);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CfamilyMousePressed

    private void Cfamily2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cfamily2MouseEntered

    }//GEN-LAST:event_Cfamily2MouseEntered

    private void Cfamily2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cfamily2MousePressed
        try {
            // TODO add your handling code here:
            families = person.getFamilies();
            person.fillComboBox(Cfamily2, families);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Cfamily2MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int servantID = -1;
        if(Cname.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null,  "رجاء اختيار الخادم الجديد ", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] servant = ((String)Cname.getSelectedItem()).split("\\s+");
        try{
            if(servant.length == 4){
                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? AND ThirdName = ? AND FourthName = ? LIMIT 1");
                pst.setString(1, servant[0]);
                pst.setString(2, servant[1]);
                pst.setString(3, servant[2]);
                pst.setString(4, servant[3]);
                rs = pst.executeQuery();
                if(rs.next())
                servantID = rs.getInt(1);
            }else if(servant.length == 3){
                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? AND ThirdName = ? LIMIT 1");
                pst.setString(1, servant[0]);
                pst.setString(2, servant[1]);
                pst.setString(3, servant[2]);
                rs = pst.executeQuery();
                if(rs.next())
                servantID = rs.getInt(1);
            }else if(servant.length == 2){
                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? LIMIT 1");
                pst.setString(1, servant[0]);
                pst.setString(2, servant[1]);
                rs = pst.executeQuery();
                if(rs.next())
                servantID = rs.getInt(1);
            }else{
                servantID = -1;
            }
            if(servantID != -1){
                int f = 0;
                pst = (PreparedStatement) con.prepareStatement("insert into Servants(ServantID) values(?)");
                pst.setInt(1, servantID);
                f = pst.executeUpdate();
                if(f > 0){
                    pst = (PreparedStatement) con.prepareStatement("delete from Distribution where PersonID = ?");
                    pst.setInt(1, servantID);
                    pst.executeUpdate();
                }
            }
            JOptionPane.showMessageDialog(null, "Done!", "Alert", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ShouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShouseKeyPressed
        // TODO add your handling code here:
        String value = Shouse.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Shouse.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Shouse.setEditable(false);
        }
    }//GEN-LAST:event_ShouseKeyPressed

    private void AssestantFamilyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssestantFamilyMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            families = person.getFamilies();
            person.fillComboBox(AssestantFamily, families);
        } catch (SQLException ex) {
            Logger.getLogger(NewServantF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AssestantFamilyMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AssestantFamily;
    private javax.swing.JComboBox<String> Cfamily;
    private javax.swing.JComboBox<String> Cfamily2;
    private javax.swing.JComboBox<String> Cname;
    private com.toedter.calendar.JDateChooser Jsdate;
    private javax.swing.JComboBox<String> Sfamily1;
    private javax.swing.JComboBox<String> Sfamily2;
    private javax.swing.JTextField Sfather;
    private javax.swing.JRadioButton Sfemale;
    private javax.swing.JTextField Sflat;
    private javax.swing.JTextField Sfloor;
    private javax.swing.JTextField Shouse;
    private javax.swing.JTextField Sjob;
    private javax.swing.JRadioButton Smale;
    private javax.swing.JTextField Smobile;
    private javax.swing.JTextField Sname1;
    private javax.swing.JTextField Sname2;
    private javax.swing.JTextField Sname3;
    private javax.swing.JTextField Sname4;
    private javax.swing.JTextField Sphone;
    private javax.swing.JTextField Sstreet1;
    private javax.swing.JTextField Sstreet2;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
