/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package church_education;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Ebrahim
 */
public class NewServedF extends javax.swing.JFrame {

    /**
     * Creates new form NewServedF
     */
    LogIn login = new LogIn();
    Connection con = login.con;
    Persons person = new Persons(con);
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs;
    
    private String check = "";
    private String frname = "";
    private String frnumber = "";
    private String frchurch = "";
    private String stname = "";
    private String stname2 = "";
    private String area = "";
    
    private String name1 = "";
    private String name2 = "";
    private String name3 = "";
    private String name4 = "";
    private java.sql.Date date = null;
    private int flat;
    private int floor;
    private int house;
    private String street1 = "";
    private String street2 = "";
    private String father = "";
    private String gender = "";
    private String phone = "";
    private String mobile = "";
    private String family = "";
    private String job = "";
    private String education = "";
    private String mnumber = "";
    private String mjob = "";
    private String fnumber = "";
    private String fjob = "";
    private String servant[];
    
    private String sname1 = "";
    private String sname2 = "";
    private String sname3 = "";
    private String sname4 = "";
    private java.sql.Date sdate = null;
    private int sflat;
    private int sfloor;
    private int shouse;
    private String sstreet1 = "";
    private String sstreet2 = "";
    private String sfather = "";
    private String sgender = "";
    private String sphone = "";
    private String smobile = "";
    private String sfamily1 = "";
    private String sfamily2 = "";
    private String sjob = "";
    private String cname = "";
    private String cfamily1 = "";
    private String cfamily2 = "";
    
//    private javafx.scene.control.TextField textField = new javafx.scene.control.TextField();
    private ArrayList<String> streetsnames = new ArrayList<>();
    private ArrayList<String> areasnames = new ArrayList<>();
    private ArrayList<String> servantsnames = new ArrayList<>();
    private ArrayList<String> fathers = new ArrayList<>();
    private ArrayList<String> families = new ArrayList<>();
    private ArrayList<String> assistance = new ArrayList<>();
    private ArrayList<String> educations = new ArrayList<>();
    private AutoComplete2 ac = new AutoComplete2();
    
    
    public NewServedF() {
        initComponents();
        buttonGroup1.add(Male);
        buttonGroup1.add(Female);
        
        
        educations.add("kg1");
        educations.add("kg2");
        educations.add("ب1");
        educations.add("ب2");
        educations.add("ب3");
        educations.add("ب4");
        educations.add("ب5");
        educations.add("ب6");
        educations.add("ع1");
        educations.add("ع2");
        educations.add("ع3");
        educations.add("ث1");
        educations.add("ث2");
        educations.add("ث3");
        educations.add("طالب جامعى");
        educations.add("خريج");
        educations.add("اخرى");
        person.fillComboBox(Education, educations);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name2 = new javax.swing.JTextField();
        Name3 = new javax.swing.JTextField();
        Name4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Flat = new javax.swing.JTextField();
        Floor = new javax.swing.JTextField();
        Street1 = new javax.swing.JTextField();
        Street2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Father = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Mobile = new javax.swing.JTextField();
        Job = new javax.swing.JTextField();
        Mnumber = new javax.swing.JTextField();
        Mjob = new javax.swing.JTextField();
        Fnumber = new javax.swing.JTextField();
        Fjob = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Servant = new javax.swing.JTextField();
        Family = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Jdate = new com.toedter.calendar.JDateChooser();
        jLabel52 = new javax.swing.JLabel();
        Education = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        House = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+4));
        jLabel1.setText("الاسم الاول");

        Name1.setFont(Name1.getFont().deriveFont(Name1.getFont().getSize()+4f));
        Name1.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+4));
        jLabel2.setText("الاسم الثانى");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+4));
        jLabel3.setText("الاسم الثالث");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+4));
        jLabel4.setText("الاسم الرابع");

        Name2.setFont(Name2.getFont().deriveFont(Name2.getFont().getSize()+4f));
        Name2.setPreferredSize(new java.awt.Dimension(200, 25));

        Name3.setFont(Name3.getFont().deriveFont(Name3.getFont().getSize()+4f));
        Name3.setPreferredSize(new java.awt.Dimension(200, 25));

        Name4.setFont(Name4.getFont().deriveFont(Name4.getFont().getSize()+4f));
        Name4.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+4));
        jLabel5.setText("تاريخ الميلاد");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, jLabel6.getFont().getSize()+4));
        jLabel6.setText("رقم الشقة");

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD, jLabel7.getFont().getSize()+4));
        jLabel7.setText("الدور");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD, jLabel8.getFont().getSize()+4));
        jLabel8.setText("العنوان ");

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, jLabel9.getFont().getSize()+4));
        jLabel9.setText("اسم الشارع");

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD, jLabel10.getFont().getSize()+4));
        jLabel10.setText("متفرع من");

        Flat.setFont(Flat.getFont().deriveFont(Flat.getFont().getSize()+4f));
        Flat.setPreferredSize(new java.awt.Dimension(200, 25));
        Flat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FlatKeyPressed(evt);
            }
        });

        Floor.setFont(Floor.getFont().deriveFont(Floor.getFont().getSize()+4f));
        Floor.setPreferredSize(new java.awt.Dimension(200, 25));
        Floor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FloorKeyPressed(evt);
            }
        });

        Street1.setFont(Street1.getFont().deriveFont(Street1.getFont().getSize()+4f));
        Street1.setPreferredSize(new java.awt.Dimension(200, 25));
        Street1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Street1MouseEntered(evt);
            }
        });

        Street2.setFont(Street2.getFont().deriveFont(Street2.getFont().getSize()+4f));
        Street2.setPreferredSize(new java.awt.Dimension(200, 25));
        Street2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Street2MouseEntered(evt);
            }
        });

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, jLabel11.getFont().getSize()+4));
        jLabel11.setText("اب الاعتراف ابونا");

        Father.setFont(Father.getFont().deriveFont(Father.getFont().getSize()+4f));
        Father.setPreferredSize(new java.awt.Dimension(200, 25));
        Father.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FatherMouseEntered(evt);
            }
        });

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getStyle() | java.awt.Font.BOLD, jLabel12.getFont().getSize()+4));
        jLabel12.setText("النوع");

        Male.setFont(Male.getFont().deriveFont(Male.getFont().getStyle() | java.awt.Font.BOLD, Male.getFont().getSize()+4));
        Male.setText("ذكر");
        Male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaleMouseClicked(evt);
            }
        });
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setFont(Female.getFont().deriveFont(Female.getFont().getStyle() | java.awt.Font.BOLD, Female.getFont().getSize()+4));
        Female.setText("انثى");

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getStyle() | java.awt.Font.BOLD, jLabel13.getFont().getSize()+4));
        jLabel13.setText("التليفون");

        jLabel14.setFont(jLabel14.getFont().deriveFont(jLabel14.getFont().getStyle() | java.awt.Font.BOLD, jLabel14.getFont().getSize()+4));
        jLabel14.setText("الموبايل");

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getStyle() | java.awt.Font.BOLD, jLabel15.getFont().getSize()+4));
        jLabel15.setText("العمل");

        jLabel16.setFont(jLabel16.getFont().deriveFont(jLabel16.getFont().getStyle() | java.awt.Font.BOLD, jLabel16.getFont().getSize()+4));
        jLabel16.setText("الاسرة");

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getStyle() | java.awt.Font.BOLD, jLabel17.getFont().getSize()+4));
        jLabel17.setText("موبايل الام");

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getStyle() | java.awt.Font.BOLD, jLabel18.getFont().getSize()+4));
        jLabel18.setText("عمل الام");

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getStyle() | java.awt.Font.BOLD, jLabel19.getFont().getSize()+4));
        jLabel19.setText("موبايل الاب");

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getStyle() | java.awt.Font.BOLD, jLabel20.getFont().getSize()+4));
        jLabel20.setText("عمل الاب");

        Phone.setFont(Phone.getFont().deriveFont(Phone.getFont().getSize()+4f));
        Phone.setPreferredSize(new java.awt.Dimension(200, 25));
        Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhoneKeyPressed(evt);
            }
        });

        Mobile.setFont(Mobile.getFont().deriveFont(Mobile.getFont().getSize()+4f));
        Mobile.setPreferredSize(new java.awt.Dimension(200, 25));
        Mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MobileKeyPressed(evt);
            }
        });

        Job.setFont(Job.getFont().deriveFont(Job.getFont().getSize()+4f));
        Job.setPreferredSize(new java.awt.Dimension(200, 25));

        Mnumber.setFont(Mnumber.getFont().deriveFont(Mnumber.getFont().getSize()+4f));
        Mnumber.setPreferredSize(new java.awt.Dimension(200, 25));
        Mnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MnumberKeyPressed(evt);
            }
        });

        Mjob.setFont(Mjob.getFont().deriveFont(Mjob.getFont().getSize()+4f));
        Mjob.setPreferredSize(new java.awt.Dimension(200, 25));

        Fnumber.setFont(Fnumber.getFont().deriveFont(Fnumber.getFont().getSize()+4f));
        Fnumber.setPreferredSize(new java.awt.Dimension(200, 25));
        Fnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FnumberKeyPressed(evt);
            }
        });

        Fjob.setFont(Fjob.getFont().deriveFont(Fjob.getFont().getSize()+4f));
        Fjob.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getStyle() | java.awt.Font.BOLD, jLabel21.getFont().getSize()+4));
        jLabel21.setText("الخادم المسؤل");

        Servant.setFont(Servant.getFont().deriveFont(Servant.getFont().getSize()+4f));
        Servant.setPreferredSize(new java.awt.Dimension(200, 25));
        Servant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ServantMouseEntered(evt);
            }
        });

        Family.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FamilyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FamilyMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FamilyMousePressed(evt);
            }
        });

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getStyle() | java.awt.Font.BOLD, jButton1.getFont().getSize()+4));
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel52.setFont(jLabel52.getFont().deriveFont(jLabel52.getFont().getStyle() | java.awt.Font.BOLD, jLabel52.getFont().getSize()+4));
        jLabel52.setText("المستوى الدراسى");

        jLabel53.setFont(jLabel53.getFont().deriveFont(jLabel53.getFont().getStyle() | java.awt.Font.BOLD, jLabel53.getFont().getSize()+4));
        jLabel53.setText("رقم المنزل");

        House.setFont(House.getFont().deriveFont(House.getFont().getSize()+4f));
        House.setPreferredSize(new java.awt.Dimension(200, 25));
        House.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HouseKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Family, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Mobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Job, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Servant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Fjob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Fnumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Education, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Mnumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Mjob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(House, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Flat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Floor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Female)
                                .addGap(94, 94, 94)
                                .addComponent(Male))
                            .addComponent(Street1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Street2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Father, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Female)
                                .addComponent(Male))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Flat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(Mjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel53)
                                            .addComponent(House, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(Fnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(Street1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(Street2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(Father, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(Family, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(Job, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel52)
                                    .addComponent(Education, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Mnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Servant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(45, 45, 45)))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FlatKeyPressed
        String value = Flat.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Flat.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Flat.setEditable(false);
        }
    }//GEN-LAST:event_FlatKeyPressed

    private void FloorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FloorKeyPressed
        String value = Floor.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Floor.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Floor.setEditable(false);
        }
    }//GEN-LAST:event_FloorKeyPressed

    private void Street1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Street1MouseEntered
        try {
            streetsnames = person.getStreetsNames();
            ac.autoComplete(Street1, streetsnames);
        } catch (SQLException ex) {
            Logger.getLogger(NewServedF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Street1MouseEntered

    private void Street2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Street2MouseEntered
        try {
            streetsnames = person.getStreetsNames();
            ac.autoComplete(Street2, streetsnames);
        } catch (SQLException ex) {
            Logger.getLogger(NewServedF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Street2MouseEntered

    private void FatherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FatherMouseEntered
        try {
            fathers = person.getFathers();
            ac.autoComplete(Father, fathers);
        } catch (SQLException ex) {
            Logger.getLogger(NewServedF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FatherMouseEntered

    private void MaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaleMouseClicked

    }//GEN-LAST:event_MaleMouseClicked

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void PhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneKeyPressed
        String value = Phone.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Phone.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Phone.setEditable(false);
        }
    }//GEN-LAST:event_PhoneKeyPressed

    private void MobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobileKeyPressed
        String value = Mobile.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Mobile.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Mobile.setEditable(false);
        }
    }//GEN-LAST:event_MobileKeyPressed

    private void MnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MnumberKeyPressed
        String value = Mnumber.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Mnumber.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Mnumber.setEditable(false);
        }
    }//GEN-LAST:event_MnumberKeyPressed

    private void FnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnumberKeyPressed
        String value = Fnumber.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Fnumber.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            Fnumber.setEditable(false);
        }
    }//GEN-LAST:event_FnumberKeyPressed

    private void ServantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServantMouseEntered
        try {
            servantsnames = person.getServantsNames();
            ac.autoComplete(Servant, servantsnames);
        } catch (SQLException ex) {
            Logger.getLogger(NewServedF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ServantMouseEntered

    private void FamilyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FamilyMouseEntered

    }//GEN-LAST:event_FamilyMouseEntered

    private void FamilyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FamilyMousePressed
        
    }//GEN-LAST:event_FamilyMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
//            pst = (PreparedStatement) con.prepareStatement("Select StreetID from Streets Where StreetName = ?");
//            pst.setString(1, "null");
//            rs = pst.executeQuery();
//            if(!rs.next()){
//                pst = (PreparedStatement) con.prepareStatement("insert into Streets(StreetName) values(?)");
//                pst.setString(1, "null");
//                pst.executeUpdate();
//            }
//            pst = (PreparedStatement) con.prepareStatement("Select FatherID from Fathers Where Name = ?");
//            pst.setString(1, "null");
//            rs = pst.executeQuery();
//            if(!rs.next()){
//                pst = (PreparedStatement) con.prepareStatement("insert into Fathers(Name) values(?)");
//                pst.setString(1, "null");
//                pst.executeUpdate();
//            }

            name1 = person.FixString(Name1.getText());
            name2 = person.FixString(Name2.getText());
            if(name1.isEmpty()){
                JOptionPane.showMessageDialog(null,  "رجاء ادخل اسم المخدوم", "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(name2.isEmpty()){
                JOptionPane.showMessageDialog(null, "رجاء ادخل الاسم الثانى ", "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }
            name3 = Name3.getText();
            name4 = Name4.getText();
            if(Jdate.getDate() != null)
            date = new java.sql.Date(Jdate.getDate().getTime());
            if(!Flat.getText().isEmpty())
            flat = Integer.parseInt(Flat.getText());
            if(!Floor.getText().isEmpty())
            floor = Integer.parseInt(Floor.getText());
            if(!House.getText().isEmpty())
            house = Integer.parseInt(House.getText());
            street1 = Street1.getText();
            street2 = Street2.getText();
            father = Father.getText();
            if(Female.isSelected()){
                gender = "Female";
            }else if(Male.isSelected()){
                gender = "Male";
            }
            if(!Phone.getText().isEmpty())
            phone = Phone.getText();
            if(!Mobile.getText().isEmpty())
            mobile = Mobile.getText();
            family = (String)Family.getSelectedItem();
            job = Job.getText();
            education = (String)Education.getSelectedItem();
            if(!Mnumber.getText().isEmpty())
            mnumber = Mnumber.getText();
            mjob = Mjob.getText();
            if(!Fnumber.getText().isEmpty())
            fnumber = Fnumber.getText();
            fjob = Fjob.getText();
            servant = Servant.getText().split("\\s+");
            int stID1 = -1;
            if(!street1.isEmpty()){
                pst = (PreparedStatement) con.prepareStatement("SELECT StreetID FROM Streets WHERE StreetName = ? LIMIT 1");
                pst.setString(1, street1);
                rs = pst.executeQuery();
                if(rs.next())
                stID1 = rs.getInt("StreetID");
            }
            int stID2 = -1;
            if(!street2.isEmpty()){
                pst = (PreparedStatement) con.prepareStatement("SELECT StreetID FROM Streets WHERE StreetName = ? LIMIT 1");
                pst.setString(1, street2);
                rs = pst.executeQuery();
                if(rs.next())
                stID2 = rs.getInt("StreetID");
            }
            int fatherID = -1;
            if(!father.isEmpty()){
                pst = (PreparedStatement) con.prepareStatement("SELECT FatherID FROM Fathers WHERE Name = ? LIMIT 1");
                pst.setString(1,father);
                rs = pst.executeQuery();
                if(rs.next())
                fatherID = rs.getInt("FatherID");
            }

            int servantID = 0;
            if(servant.length == 4){
                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? AND ThirdName = ? AND FourthName = ? LIMIT 1");
                pst.setString(1, servant[0]);
                pst.setString(2, servant[1]);
                pst.setString(3, servant[2]);
                pst.setString(4, servant[3]);
                rs = pst.executeQuery();
                if(rs.next())
                servantID = rs.getInt("PersonID");
            }else if(servant.length == 3){
                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? AND ThirdName = ? LIMIT 1");
                pst.setString(1, servant[0]);
                pst.setString(2, servant[1]);
                pst.setString(3, servant[2]);
                rs = pst.executeQuery();
                if(rs.next())
                servantID = rs.getInt("PersonID");
            }else if(servant.length == 2){
                pst = (PreparedStatement) con.prepareStatement("SELECT PersonID FROM Persons WHERE FirstName = ? AND SecondName = ? LIMIT 1");
                pst.setString(1, servant[0]);
                pst.setString(2, servant[1]);
                rs = pst.executeQuery();
                if(rs.next())
                servantID = rs.getInt("PersonID");
            }else{
                servantID = -1;
            }
            pst = (PreparedStatement) con.prepareStatement("select * from Persons where " +
                "FirstName = ? and (MotherMobile = ? or FatherMobile = ? or Mobile = ? or Telephon = ?)");
            pst.setString(1, name1);
            pst.setString(2, mnumber);
            pst.setString(3, fnumber);
            pst.setString(4, mobile);
            pst.setString(5, phone);
            rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "هذا الشخص موجود بالفعل يمكنك البحث عنه عن طريق  ID : " + rs.getInt("PersonID"), "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }

            pst = (PreparedStatement) con.prepareStatement("INSERT INTO Persons(FirstName, SecondName, ThirdName, " +
                "FourthName, DOB, ApartmentNumber, FloorNumber, Job, Telephon, Mobile, Gender, FatherID, StreetID, " +
                "StreetID2, MotherJob, MotherMobile, FatherMobile, FatherJob, EducationalLevel, House)" +
                " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setString(1, name1);
            pst.setString(2, name2);
            pst.setString(3, name3);
            pst.setString(4, name4);
            pst.setDate(5, date);
            pst.setInt(6, flat);
            pst.setInt(7, floor);
            pst.setString(8, job);
            pst.setString(9, phone);
            pst.setString(10, mobile);
            pst.setString(11, gender);
            if(father.isEmpty())
                pst.setString(12, null);
            else
                pst.setInt(12, fatherID);
            if(street1.isEmpty())
                pst.setString(13, null);
            else
                pst.setInt(13, stID1);
            if(street2.isEmpty())
                pst.setString(14, null);
            else
                pst.setInt(14, stID2);
            pst.setString(15, mjob);
            pst.setString(16, mnumber);
            pst.setString(17, fjob);
            pst.setString(18, fnumber);
            pst.setString(19, education);
            pst.setInt(20, house);
            pst.executeUpdate();

            Name1.setText("");
            Name2.setText("");
            Name3.setText("");
            Name4.setText("");
            //            date.setDate(2020);
            Flat.setText("");
            Floor.setText("");
            House.setText("");
            Street1.setText("");
            Street2.setText("");
            Father.setText("");
            buttonGroup1.clearSelection();
            Phone.setText("");
            Mobile.setText("");
            Job.setText("");
            Mnumber.setText("");
            Mjob.setText("");
            Fnumber.setText("");
            Fjob.setText("");
            Servant.setText("");
            Family.setSelectedItem(null);
            Education.setSelectedItem(null);
            Jdate.setDate(null);

            int servedID = -1;
            rs = pst.executeQuery("Select LAST_INSERT_ID()");
            if(rs.next())
            servedID = rs.getInt(1);
            if(servantID != -1){
                pst = (PreparedStatement) con.prepareStatement("INSERT INTO Lists(ServantID, ServedID) VALUES (?, ?)");
                pst.setInt(1, servantID);
                pst.setInt(2, servedID);
                pst.executeUpdate();
            }

            if(family != null)
                person.addDistribution(family, servedID, 1);
            JOptionPane.showMessageDialog(null, "Done!", "Alert", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(NewServedF.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some thing wronge hapen!", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HouseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HouseKeyPressed
        // TODO add your handling code here:
        String value = House.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            House.setEditable(true);
        }else if(evt.getKeyChar() != '\b') {
            House.setEditable(false);
        }
    }//GEN-LAST:event_HouseKeyPressed

    private void FamilyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FamilyMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            families = person.getFamilies();
            person.fillComboBox(Family, families);
        } catch (SQLException ex) {
            Logger.getLogger(NewServedF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FamilyMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Education;
    private javax.swing.JComboBox<String> Family;
    private javax.swing.JTextField Father;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField Fjob;
    private javax.swing.JTextField Flat;
    private javax.swing.JTextField Floor;
    private javax.swing.JTextField Fnumber;
    private javax.swing.JTextField House;
    private com.toedter.calendar.JDateChooser Jdate;
    private javax.swing.JTextField Job;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField Mjob;
    private javax.swing.JTextField Mnumber;
    private javax.swing.JTextField Mobile;
    private javax.swing.JTextField Name1;
    private javax.swing.JTextField Name2;
    private javax.swing.JTextField Name3;
    private javax.swing.JTextField Name4;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Servant;
    private javax.swing.JTextField Street1;
    private javax.swing.JTextField Street2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
